### ISSUE TITLE
Doesn't display power

### ISSUE THREAD

**Issue by MattiasOz** [magillos/Plasma-6-power-usage-widget#3]
It just says "Reading current". I tried adding the EV.sh file. *QML_XHR_ALLOW_FILE_READ* seems to have been exported successfully but nothing changed. I don't know how the code works so ask for whatever information is needed.

**Comment by magillos** [comment]
It shouldn't need that EV any more and it's safer to not use that file (it allows to read other plasmoids from disk, although Plasma 5 didn't have issue with that AFAIK).
Could you post output of  `ls  /sys/class/power_supply/`?

**Comment by MattiasOz** [comment]
`❯ ls /sys/class/power_supply/`
`ACAD  BAT1  ucsi-source-psy-USBC000:001  ucsi-source-psy-USBC000:002`

**Comment by magillos** [comment]
Is it USB C charger you are using? 
Could you run this a let me know what is it showing?
`cd ~/.local/share/plasma/plasmoids/`
`QT_LOGGING_RULES="qt.qml.connections=true" plasmawindowed org.kde.plasma.powerusage`

And also:
`cat /sys/class/power_supply/ucsi-source-psy-USBC000:001/current_now`
and 
`cat /sys/class/power_supply/ucsi-source-psy-USBC000:002/current_now`
and also this:
`cat  /sys/class/power_supply/BAT1/current_now`

**Comment by MattiasOz** [comment]
Yes, it charges by usb-c. It's not charging while I run these commands: 

```bash
❯ QT_LOGGING_RULES="qt.qml.connections=true" plasmawindowed org.kde.plasma.powerusage
kf.plasma.quick: Applet preload policy set to 1
qml: 0
qml: Battery found: /sys/class/power_supply/BAT1
qml: AC adapter found: /sys/class/power_supply/ACAD
qml: Error reading file: cat /sys/class/power_supply/BAT1/current_now stderr: /usr/bin/cat: /sys/class/power_supply/BAT1/current_now: No such file or directory

qml: Error reading file: cat /sys/class/power_supply/BAT1/current_now stderr: /usr/bin/cat: /sys/class/power_supply/BAT1/current_now: No such file or directory

qml: Error reading file: cat /sys/class/power_supply/BAT1/current_now stderr: /usr/bin/cat: /sys/class/power_supply/BAT1/current_now: No such file or directory
```

```bash
❯ cat /sys/class/power_supply/ucsi-source-psy-USBC000:001/current_now
0
```

```bash
❯ cat /sys/class/power_supply/ucsi-source-psy-USBC000:002/current_now
0
```

```bash
❯ cat  /sys/class/power_supply/BAT1/current_now
cat: /sys/class/power_supply/BAT1/current_now: No such file or directory
```

```bash
❯ ls -1 /sys/class/power_supply/BAT1/
alarm
capacity
capacity_level
cycle_count
device
energy_full
energy_full_design
energy_now
hwmon2
manufacturer
model_name
power
power_now
present
serial_number
status
subsystem
technology
type
uevent
voltage_min_design
voltage_now
```

*power_now* seems to be µW. *capacity* is percentage left. *energy_now* seems to be µWh.

**Comment by magillos** [comment]
I'm not sure how to bite this. Wattage in the widget is calculated by multiplying voltage and current, as read from battery's voltage_now and current_now files. You don't seems to have current_now file there and your USB C devices won't be helpful, showing 0. 

Could you show what `cat  /sys/class/power_supply/BAT1/power_now` shows on battery and when USB charger is plugged in. And also ` cat /sys/class/power_supply/ACAD/online` (hopefully you have it).

**Comment by MattiasOz** [comment]
```bash
❯ cat  /sys/class/power_supply/BAT1/power_now
25443000
```
```bash
❯ cat /sys/class/power_supply/ACAD/online
1
 ```
It's **0** when not plugged in. 
Additionally: `/sys/class/power_supply/BAT1/status` says "Discharging", "Charging" or "Not charging" (when plugged in but not charging)

**Comment by MattiasOz** [comment]
Also, power_now is never negative. It's just the absolute value of change. I suppose you'd have to use ACAD/online to determine the sign.

**Comment by magillos** [comment]
I added test.plasmoid file to the main page. Could you test it  with `QT_LOGGING_RULES="qt.qml.connections=true" plasmoidviewer --applet test.plasmoid` ?

**Comment by MattiasOz** [comment]
I might've done it wrong but I installed "plasma-sdk", uninstalled the old application and installed the test one from the file. 
```bash
❯ QT_LOGGING_RULES="qt.qml.connections=true" plasmoidviewer --applet test.plasmoid       
QML debugging is enabled. Only use this in a safe environment.
qml: View QML loaded
kf.plasma.quick: Applet preload policy set to 1
file:///usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/main.qml:196:25: QML FolderViewDropArea (parent or ancestor of QQuickLayoutAttached): Binding loop detected for property "minimumWidth"
Toolbox not loading, toolbox package is either invalid or disabled.
qml: New Containment: ContainmentItem_QML_47(0x55e6b6b48d30, "desktop")
kf.plasma.core: Applet invalid: Cannot find a package for "test.plasmoid"
kf.plasma.quick: File name empty!
kf.plasma.quick: error when loading applet "" QList("This Widget was written for an unknown older version of Plasma and is not compatible with Plasma 6. Please contact the widget's author for an updated version.Error loading Applet: package does not exist. ")
"Applet test.plasmoid does not exist."
^C
```
It seems not to exist. Although when adding the widget normally it appeared under the same name maybe there's something weird with that. 

I tried running the following instead and it seems to work albeit only in that environment. 
```bash
❯ QT_LOGGING_RULES="qt.qml.connections=true" plasmoidviewer --applet org.kde.plasma.powerusage 
QML debugging is enabled. Only use this in a safe environment.
qml: View QML loaded
kf.plasma.quick: Applet preload policy set to 1
file:///usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/main.qml:196:25: QML FolderViewDropArea (parent or ancestor of QQuickLayoutAttached): Binding loop detected for property "minimumWidth"
Toolbox not loading, toolbox package is either invalid or disabled.
qml: New Containment: ContainmentItem_QML_47(0x5568fa49e8a0, "desktop")
qml: Battery found: /sys/class/power_supply/BAT1
qml: AC adapter found: /sys/class/power_supply/ACAD
qml: Device has power_now file
qml: Device has power_now file
qml: Device has power_now file
qml: Device has power_now file
qml: Device has power_now file
qml: Device has power_now file
qml: Device has power_now file
qml: Device has power_now file
```

It doesn't run in normally though...

**Comment by MattiasOz** [comment]
Plasmoidviewer had a window where it said "-7.7W" btw.

**Comment by MattiasOz** [comment]
Oh, actually it seems to be working after a reboot :)
![image](https://github.com/user-attachments/assets/98beb1ea-a4f8-4136-b234-d6dfd4a53a9c)

**Comment by magillos** [comment]
Happy days! What is your device? I'd like to add that info to the changelog. 
(Also, remove EV.sh file from ~/.config/plasma-workspace/env/, if you haven't already. It's not needed and some malicious plasmoid or other app could potentially read from your disk with it there).

**Comment by MattiasOz** [comment]
Gotcha. I have a Lenovo Ideapad 5 Pro. Arch btw :P

**Comment by magillos** [comment]
It's now updated on KDE Store and here. Your testing plasmoid had number localization hardcoded (coma not dot, regardless of your Plasma language setting), so if you're bothered by that just reinstall from one of those places. Arch btw too.
