### ISSUE TITLE
Log Spam

### ISSUE THREAD

**Issue by alou-S** [magillos/Plasma-6-power-usage-widget#4]
The applet constantly keeps outputting `qml: Device has power_now file` into the console log which inturn is forwarded to the journal logs as `plasmashell[2592113]: qml: Device has power_now file` It does this twice every two seconds. 

This often leads to the journal being flooded by the unneeded message.

A possible fix would be to track for the state of the power_now file changing. And only when the state changes it outputs to console.

**Comment by magillos** [comment]
I don't seem to have that issue but could you check testing.plasmoid on main Github if it's better?

**Comment by alou-S** [comment]
Yup the latest commit fixes the issue entirely.

**Comment by magillos** [comment]
Thanks for testing and closing the issue. It's now been updated on Girhub and KDE store.
